<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ass\\XmlSecurity' => array($vendorDir . '/ass/xmlsecurity/src'),
    'Verifalia\\' => array($vendorDir . '/verifalia/sdk/lib'),
    'Svg\\' => array($vendorDir . '/phenx/php-svg-lib/src'),
    'Sabberworm\\CSS' => array($vendorDir . '/sabberworm/php-css-parser/lib'),
    'Resque' => array($vendorDir . '/chrisboulton/php-resque/lib'),
    'BeSimple\\WsdlToPhp' => array($vendorDir . '/besimple/wsdl2php/src'),
    'BeSimple\\SoapCommon' => array($vendorDir . '/besimple/soap-common'),
);
